#!/usr/bin/env groovy
/*  VINOTH created script for python scripts         */
/*  VINOTH Added this into jenkins pipeline          */
/*  VINOTH Added auto directory delete feature       */
node {
    def GIT_URL = "https://github.com/vinothsundararajan/python-scripts.git"
    def BUILD_NUMBER 
    def GITHUB_PROJ = "C:\\Vinoth\\Python\\GitHub"
    def VERSION = 1.0
    def TOTAL_COUNT = 6

    properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', numToKeepStr: '10')), disableConcurrentBuilds(), pipelineTriggers([])])
    
    stage('Checkout') {
        deleteDir()
        checkout scm
    }
    stage('Build') {
        echo 'Building..'
        bat """
            mkdir %GITHUB_PROJ%
            cd ${GITHUB_PROJ};
            git clone -b master ${GIT_URL} ${VERSION}_%BUILD_NUMBER%
            cd ${VERSION}_%BUILD_NUMBER%
            git pull origin master --tags
            echo "Python-scripts Clone done"
            @echo off
            for /f "skip=5 delims=" %%a in ('dir /b /o-d /ad') do rd /s /q "%%a"
            pause
            cd ..
        """
    }
    stage('Deploy') {
        echo 'Deploying....'
    }
}
